package objects

// ASM types and names
const (
	AL        = string("al")
	BL        = string("bl")
	AX        = string("ax")
	MOV       = string("mov")
	SUB       = string("sub")
	DIV       = string("div")
	MUL       = string("mul")
	ADD       = string("add")
	EAX       = string("eax")
	EBX       = string("ebx")
	ECX       = string("ecx")
	EDX       = string("edx")
	INT       = string("int")
	i386_PROC = string("0x80")
	AND       = string("and")
	OR        = string("or")
	XOR       = string("xor")
	NOT       = string("not")
	CMP       = string("xmp")
	JE        = string("je")
	JLE       = string("jle")
	JMP       = string("jmp")
	JZ        = string("jz")
	JNE       = string("jne")
	JNZ       = string("jnz")
	JG        = string("jg")
	JNLE      = string("jnle")
	JGE       = string("jge")
	JL        = string("jl")
	JNGE      = string("jnge")
	JNG       = string("jng")
	JXCZ      = string("jxcz")
	JC        = string("jc")
	JNC       = string("jnc")
	JO        = string("jo")
	JNO       = string("jno")
	JP        = string("jp")
	JPE       = string("jpe")
	JNP       = string("jnp")
	JPO       = string("jpo")
	JS        = string("js")
	JNS       = string("js")
	LOOP      = string("loop")
	DB        = string("db")
	SYS_EXIT  = string("1")
	SYS_READ  = string("3")
	SYS_WRITE = string("4")
	STDIN     = string("0")
	STDOUT    = string("1")
	PRINT_CLI = string("print_cli")
	INPUT_CLI = string("input_cli")
	MUL_INT   = string("mul_int")
	DIV_INT   = string("div_int")
)
